// Doctor packet PDF generator. Pure server-side render via pdfkit so we
// don't ship any chrome/puppeteer deps. Per docs/03 Flow 11 — outputs a
// scannable summary the user can hand to a clinician.

import { Injectable, Logger, NotFoundException } from "@nestjs/common";
import PDFDocument from "pdfkit";
import { Readable } from "node:stream";

import { POLICY_VERSION } from "@familia/consent-engine";

import { AuditService } from "../audit/audit.service";
import { PrismaService } from "../common/prisma.service";

type ReqMeta = { actorUserId: string; clientIp?: string | null };

export type PacketOptions = {
  reason?: string;
  includeMedications?: boolean;
  includeConditions?: boolean;
  includeAllergies?: boolean;
  includeRecentEncounters?: boolean;
};

@Injectable()
export class PacketService {
  private readonly log = new Logger("PacketService");

  constructor(
    private readonly db: PrismaService,
    private readonly audit: AuditService,
  ) {}

  async generate(opts: PacketOptions, meta: ReqMeta): Promise<NodeJS.ReadableStream> {
    const user = await this.db.user.findUnique({ where: { id: meta.actorUserId } });
    if (!user) throw new NotFoundException("user");

    const [meds, conditions, allergies, encounters] = await Promise.all([
      opts.includeMedications !== false
        ? this.db.medication.findMany({
            where: { userId: meta.actorUserId, status: "active" },
            orderBy: { name: "asc" },
          })
        : Promise.resolve([]),
      opts.includeConditions !== false
        ? this.db.condition.findMany({
            where: { userId: meta.actorUserId, status: "active" },
            orderBy: { name: "asc" },
          })
        : Promise.resolve([]),
      opts.includeAllergies !== false
        ? this.db.allergy.findMany({
            where: { userId: meta.actorUserId },
            orderBy: { allergen: "asc" },
          })
        : Promise.resolve([]),
      opts.includeRecentEncounters !== false
        ? this.db.encounter.findMany({
            where: { userId: meta.actorUserId },
            orderBy: { startTime: "desc" },
            take: 8,
          })
        : Promise.resolve([]),
    ]);

    const doc = new PDFDocument({
      size: "LETTER",
      margins: { top: 56, bottom: 56, left: 56, right: 56 },
      info: {
        Title: "FAMILIA — Patient packet",
        Author: "FAMILIA",
        Subject: opts.reason ?? "Health summary",
      },
    });
    const stream = Readable.from(toAsyncIterable(doc));
    // Render then end. doc.end() must come after content is queued.
    void this.render(doc, {
      user,
      meds,
      conditions,
      allergies,
      encounters,
      reason: opts.reason,
    });

    // Audit (fire-and-forget, but record).
    void this.audit
      .write({
        eventType: "export.generated",
        subjectId: meta.actorUserId,
        actorUserId: meta.actorUserId,
        targetUserId: meta.actorUserId,
        fromState: null,
        toState: "generated",
        metadata: {
          format: "pdf",
          reason: opts.reason ?? null,
          counts: {
            medications: meds.length,
            conditions: conditions.length,
            allergies: allergies.length,
            encounters: encounters.length,
          },
        },
        policyVersion: POLICY_VERSION,
        requestSource: "api",
        clientIp: meta.clientIp ?? null,
      })
      .catch((err) => this.log.warn(`audit write failed: ${(err as Error).message}`));

    return stream;
  }

  private async render(
    doc: PDFKit.PDFDocument,
    args: {
      user: { firstName: string; lastName: string | null; dateOfBirth: Date | null; bloodType: string | null };
      meds: Array<{ name: string; doseText: string | null; frequencyText: string | null; reason: string | null }>;
      conditions: Array<{ name: string; severity: string | null; onsetDate: Date | null }>;
      allergies: Array<{ allergen: string; reaction: string | null; severity: string }>;
      encounters: Array<{ type: string; providerName: string | null; facilityName: string | null; startTime: Date | null; reason: string | null }>;
      reason?: string;
    },
  ) {
    const fullName = [args.user.firstName, args.user.lastName].filter(Boolean).join(" ");

    // Header.
    doc.fontSize(20).text("Patient health summary", { align: "left" });
    doc.moveDown(0.2);
    doc.fontSize(10).fillColor("#666").text("Generated by FAMILIA — patient-controlled record. Not a clinical document.");
    doc.fillColor("#000");
    doc.moveDown(1);

    // Patient block.
    doc.fontSize(12).text(`Name: ${fullName || "—"}`);
    if (args.user.dateOfBirth)
      doc.text(`Date of birth: ${args.user.dateOfBirth.toISOString().slice(0, 10)}`);
    if (args.user.bloodType) doc.text(`Blood type: ${args.user.bloodType}`);
    if (args.reason) {
      doc.moveDown(0.5);
      doc.fontSize(10).fillColor("#444").text(`For: ${args.reason}`);
      doc.fillColor("#000");
    }
    doc.moveDown(1);

    // Allergies (top of page — clinically critical).
    section(doc, "Allergies", args.allergies.length === 0 ? "None on file." : undefined);
    for (const a of args.allergies) {
      doc.fontSize(11).text(`• ${a.allergen}` + (a.severity ? `  (${a.severity})` : ""));
      if (a.reaction) doc.fontSize(10).fillColor("#444").text(`     ${a.reaction}`).fillColor("#000");
    }
    doc.moveDown(0.5);

    // Active medications.
    section(doc, "Active medications", args.meds.length === 0 ? "None on file." : undefined);
    for (const m of args.meds) {
      let line = `• ${m.name}`;
      if (m.doseText) line += `  ·  ${m.doseText}`;
      if (m.frequencyText) line += `  ·  ${m.frequencyText}`;
      doc.fontSize(11).text(line);
      if (m.reason) doc.fontSize(10).fillColor("#444").text(`     for ${m.reason}`).fillColor("#000");
    }
    doc.moveDown(0.5);

    // Active conditions.
    section(doc, "Active conditions", args.conditions.length === 0 ? "None on file." : undefined);
    for (const c of args.conditions) {
      let line = `• ${c.name}`;
      if (c.severity) line += `  ·  ${c.severity}`;
      if (c.onsetDate) line += `  ·  onset ${c.onsetDate.toISOString().slice(0, 10)}`;
      doc.fontSize(11).text(line);
    }
    doc.moveDown(0.5);

    // Recent encounters.
    section(doc, "Recent visits", args.encounters.length === 0 ? "None on file." : undefined);
    for (const e of args.encounters) {
      const when = e.startTime ? e.startTime.toISOString().slice(0, 10) : "—";
      const place = [e.providerName, e.facilityName].filter(Boolean).join(", ");
      doc.fontSize(11).text(`• ${when}  ·  ${e.type}${place ? `  ·  ${place}` : ""}`);
      if (e.reason) doc.fontSize(10).fillColor("#444").text(`     ${e.reason}`).fillColor("#000");
    }

    doc.moveDown(2);
    doc
      .fontSize(8)
      .fillColor("#666")
      .text(
        `Generated ${new Date().toISOString()} · policy ${POLICY_VERSION} · this is a patient-prepared summary, not a clinical record.`,
        { align: "center" },
      )
      .fillColor("#000");

    doc.end();
  }
}

function section(doc: PDFKit.PDFDocument, title: string, empty?: string) {
  doc.moveDown(0.5);
  doc.fontSize(13).fillColor("#000").text(title);
  doc.moveTo(doc.x, doc.y).lineTo(doc.page.width - doc.page.margins.right, doc.y).strokeColor("#ccc").stroke();
  doc.moveDown(0.3);
  if (empty) doc.fontSize(11).fillColor("#666").text(empty).fillColor("#000");
}

// pdfkit emits Node 'data' events synchronously after .end(). Wrap as async iterable.
async function* toAsyncIterable(doc: PDFKit.PDFDocument): AsyncGenerator<Buffer> {
  const chunks: Buffer[] = [];
  let resolveData: (() => void) | null = null;
  let ended = false;
  doc.on("data", (chunk: Buffer) => {
    chunks.push(chunk);
    if (resolveData) {
      resolveData();
      resolveData = null;
    }
  });
  doc.on("end", () => {
    ended = true;
    if (resolveData) {
      resolveData();
      resolveData = null;
    }
  });

  while (true) {
    if (chunks.length === 0 && !ended) {
      await new Promise<void>((r) => (resolveData = r));
    }
    while (chunks.length > 0) {
      yield chunks.shift()!;
    }
    if (ended) return;
  }
}
